import { title } from "process";
import React from "react";

//static metadata
export const metadata = {
  title: "About Page",
  description: "Generated by About Page",
};

function About() {
  return <div>About</div>;
}

export default About;
