import { title } from "process";
import React from "react";

//define title
export const metadata = {
  title: {
    absolute: "About Page",
  },
  description: "Generated by About Page",
};

function About() {
  return <div>About</div>;
}

export default About;
