export const metadata = {
  title: {
    default: "Next.js",
    template: "%s | Learn Next.js",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{ padding: "16px ", backgroundColor: "lightblue" }}
          className="p-4 bg-light-gray"
        >
          Header
        </header>
        {children}
        <footer style={{ padding: "16px ", backgroundColor: "lightblue" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
